"""presentacion area causante video

Revision ID: 2fbacac032b9
Revises: ae5e390e9adc
Create Date: 2026-07-24 01:24:58.905793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbacac032b9'
down_revision = 'ae5e390e9adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pqrs_solicitudes', sa.Column('presentacion', sa.String(length=30), nullable=True))
    op.add_column('pqrs_solicitudes', sa.Column('adjunto_video', sa.String(length=500), nullable=True))
    op.add_column('pqrs_solicitudes', sa.Column('area_causante', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pqrs_solicitudes', 'area_causante')
    op.drop_column('pqrs_solicitudes', 'adjunto_video')
    op.drop_column('pqrs_solicitudes', 'presentacion')
    # ### end Alembic commands ###
