"""crear tablas autorizaciones

Revision ID: 5ae26c88bd8c
Revises: 06dc27cff8cf
Create Date: 2026-07-09 00:59:03.560701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae26c88bd8c'
down_revision = '06dc27cff8cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_autorizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('area_autorizadora', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_autorizacion_id'), 'tipos_autorizacion', ['id'], unique=False)
    op.create_index(op.f('ix_tipos_autorizacion_tenant_id'), 'tipos_autorizacion', ['tenant_id'], unique=False)
    op.create_table('autorizaciones_pqrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pqrs_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('solicitado_por', sa.Integer(), nullable=False),
    sa.Column('autorizado_por', sa.Integer(), nullable=True),
    sa.Column('comentario_solicitud', sa.Text(), nullable=True),
    sa.Column('comentario_respuesta', sa.Text(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['autorizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pqrs_id'], ['pqrs_solicitudes.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_autorizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autorizaciones_pqrs_id'), 'autorizaciones_pqrs', ['id'], unique=False)
    op.create_index(op.f('ix_autorizaciones_pqrs_pqrs_id'), 'autorizaciones_pqrs', ['pqrs_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autorizaciones_pqrs_pqrs_id'), table_name='autorizaciones_pqrs')
    op.drop_index(op.f('ix_autorizaciones_pqrs_id'), table_name='autorizaciones_pqrs')
    op.drop_table('autorizaciones_pqrs')
    op.drop_index(op.f('ix_tipos_autorizacion_tenant_id'), table_name='tipos_autorizacion')
    op.drop_index(op.f('ix_tipos_autorizacion_id'), table_name='tipos_autorizacion')
    op.drop_table('tipos_autorizacion')
    # ### end Alembic commands ###
