"""autorizaciones_pqrs

Revision ID: ab08cec09d70
Revises: 37174d0a943a
Create Date: 2026-07-08 12:34:40.919843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab08cec09d70'
down_revision = '37174d0a943a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autorizaciones_pqrs')
    op.drop_table('tipos_autorizacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_autorizacion',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tipos_autorizacion_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area_autorizadora', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='tipos_autorizacion_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tipos_autorizacion_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('autorizaciones_pqrs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pqrs_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=False),
    sa.Column('solicitado_por', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('autorizado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comentario_solicitud', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comentario_respuesta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_solicitud', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_respuesta', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['autorizado_por'], ['users.id'], name='autorizaciones_pqrs_autorizado_por_fkey'),
    sa.ForeignKeyConstraint(['pqrs_id'], ['pqrs_solicitudes.id'], name='autorizaciones_pqrs_pqrs_id_fkey'),
    sa.ForeignKeyConstraint(['solicitado_por'], ['users.id'], name='autorizaciones_pqrs_solicitado_por_fkey'),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_autorizacion.id'], name='autorizaciones_pqrs_tipo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='autorizaciones_pqrs_pkey')
    )
    # ### end Alembic commands ###
