"""encuesta satisfaccion completa

Revision ID: ae5e390e9adc
Revises: 5ae26c88bd8c
Create Date: 2026-07-15 19:03:17.887951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5e390e9adc'
down_revision = '5ae26c88bd8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pqrs_encuestas', sa.Column('tipo_solicitud', sa.String(length=20), nullable=True))
    op.add_column('pqrs_encuestas', sa.Column('solucionada', sa.String(length=20), nullable=True))
    op.add_column('pqrs_encuestas', sa.Column('calificacion_tiempo_respuesta', sa.String(length=20), nullable=True))
    op.add_column('pqrs_encuestas', sa.Column('recomendaria', sa.Boolean(), nullable=True))
    op.drop_constraint('pqrs_solicitudes_radicado_calidad_key', 'pqrs_solicitudes', type_='unique')
    op.create_index(op.f('ix_pqrs_solicitudes_radicado_calidad'), 'pqrs_solicitudes', ['radicado_calidad'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pqrs_solicitudes_radicado_calidad'), table_name='pqrs_solicitudes')
    op.create_unique_constraint('pqrs_solicitudes_radicado_calidad_key', 'pqrs_solicitudes', ['radicado_calidad'])
    op.drop_column('pqrs_encuestas', 'recomendaria')
    op.drop_column('pqrs_encuestas', 'calificacion_tiempo_respuesta')
    op.drop_column('pqrs_encuestas', 'solucionada')
    op.drop_column('pqrs_encuestas', 'tipo_solicitud')
    # ### end Alembic commands ###
