"""cantidad presentacion

Revision ID: bdf9c3bafa3d
Revises: 2fbacac032b9
Create Date: 2026-07-25 01:07:14.422156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf9c3bafa3d'
down_revision = '2fbacac032b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pqrs_solicitudes', sa.Column('cantidad_presentacion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pqrs_solicitudes', 'cantidad_presentacion')
    # ### end Alembic commands ###
