"""adjunto evidencia en seguimiento

Revision ID: c7a1f4e8b2d3
Revises: bdf9c3bafa3d
Create Date: 2026-07-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a1f4e8b2d3'
down_revision = 'bdf9c3bafa3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'pqrs_seguimientos',
        sa.Column('adjunto_evidencia', sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pqrs_seguimientos', 'adjunto_evidencia')
    # ### end Alembic commands ###
